In [3]:
import numpy as np



In [52]:
def createStochasticMatrix(n):
    """
    Returns a random n by n stochastic matrix
    
    Parameters
    ----------
    n : integer
    
    Return
    ------
    t : matrixlike
    """
    
    t = np.random.rand(n,n)
    t2 = np.random.rand(n,n)
    idx =(t2<0.5)
    
    t[idx]=0
    
    #scale the matrix so it becomes stochastic

    for i in range(n):
        if np.sum(t[i,:])==0:
            t[i][i]=1
        else:
            t[i,:] /= np.sum(t[i,:])
    return t
    

In [5]:
print (createStochasticMatrix(4))

[[ 0.          0.84237975  0.15762025  0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.45628813  0.38571859  0.15799328  0.        ]
 [ 0.          0.          0.58600767  0.41399233]]


In [43]:
import scipy.linalg as alg

def findStationaryDistribution(t):
    """
    Returns a (the) stationary distribution of the input matrix t
    
    Parameters
    ----------
    t : stochastic matrix

    Return
    ------
    pi : stationary distribution of t
    """

    eigvalue, eigvec = alg.eig(t,left=True,right=False)
    print(eigvalue)
    print(eigvec)
    index = np.argmax(eigvalue)
    print(index)
    result = eigvec[:,index]
    
    result /= np.sum(result)
    
    return result

In [56]:
matrix = createStochasticMatrix(4)
print(matrix)
#testmatrix = np.array([[0,1,0],[0,0,1],[1,0,0]])
#print(testmatrix)
#print(findStationaryDistribution(testmatrix))
print(findStationaryDistribution(matrix))

[[ 0.17275886  0.          0.82724114  0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.93020634  0.06979366  0.          0.        ]]
[ 0.00000000+0.j  0.17275886+0.j  0.00000000+0.j  1.00000000+0.j]
[[ -2.18661445e-290   7.07106781e-001   0.00000000e+000   0.00000000e+000]
 [ -7.07106781e-001   0.00000000e+000   7.07106781e-001   0.00000000e+000]
 [  7.07106781e-001  -7.07106781e-001  -7.07106781e-001   1.00000000e+000]
 [  4.06100249e-291   0.00000000e+000   0.00000000e+000   0.00000000e+000]]
3
[ 0.  0.  1.  0.]
